// <auto-generated />
using System;
using LeaveApplication.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveApplication.API.Migrations
{
    [DbContext(typeof(MyDataContext))]
    [Migration("20230204130520_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveApplication.API.Model.LeaveApplicationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneralComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveApplicationRequests");
                });

            modelBuilder.Entity("LeaveApplication.API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Sarah Johnson",
                            Password = "Abcd1234",
                            Username = "sarahjohnson"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Michael Brown",
                            Password = "Abcd1234",
                            Username = "michaelbrown"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Elizabeth Davis",
                            ManagerId = 1,
                            Password = "Abcd1234",
                            Username = "elizabethdavis"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "William Smith",
                            ManagerId = 1,
                            Password = "Abcd1234",
                            Username = "williamsmith"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "James Wilson",
                            ManagerId = 1,
                            Password = "Abcd1234",
                            Username = "jameswilson"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Catherine White",
                            ManagerId = 1,
                            Password = "Abcd1234",
                            Username = "catherinewhite"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Jennifer Anderson",
                            ManagerId = 2,
                            Password = "Abcd1234",
                            Username = "jenniferanderson"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Christopher Lee",
                            ManagerId = 2,
                            Password = "Abcd1234",
                            Username = "christopherlee"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Susan Taylor",
                            ManagerId = 2,
                            Password = "Abcd1234",
                            Username = "susantaylor"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "David Green",
                            ManagerId = 2,
                            Password = "Abcd1234",
                            Username = "davidgreen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
